### PR TITLE
Correct invalid chiplet id for MCS units

### PR DESCRIPTION
**Pull request by MRaybuck**

### CODE REVIEW

**Review by mabaiocchi — APPROVED** [review]

**Comment by mabaiocchi** [comment]
@jimsmc Can you please merge this when you have a chance? A similar change has already been put into the romulus-xml and zaius-xml repos, and another one will be going into the witherspoon-xml repo.  This is needed for hostboot to better support partially good processors.  Thank you.

**Comment by mabaiocchi** [comment]
@bwmashak can you please review and merge this when you can?  I'm sure you've been on vacation, but we'd like to get this merged to clear the way for some upcoming Hostboot changes.  Thanks.

**Comment by dcrowell77** [comment]
I think this should be abandoned/closed, a fix was put into the processing scripts instead.

**Comment by jimsmc** [comment]
Close this pull request per Dan's comment.

**Pull request closed without merging**
